### PR TITLE
Dt 1410 node limiting

### PR DESCRIPTION
**Pull request by Macroz**
Implements node counting and limiting, and refactors previous execution time limiting. Uses a temporary fork of graphql-java until upstream can support this.

### CODE REVIEW

**Comment by samuliheljo** [comment]
I'm having some problems:

1. Start OTP like so:
java -jar target/otp-1.1.0-SNAPSHOT-shaded.jar --server --port 8000 --securePort 8443 --basePath /Users/samuli/github/OpenTripPlanner --graphs ./ --router router-hsl

2. Use current UI master, configure it to use localhost OTP

3. Nearest tab does not work, routes don't work

15:16:05.576 INFO (ExecutionStrategy.java:44) Exception while fetching data
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Double
	at org.opentripplanner.index.IndexGraphQLSchema.lambda$new$149(IndexGraphQLSchema.java:2051) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:42) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
	at org.opentripplanner.index.ResourceConstrainedExecutorServiceExecutionStrategy.lambda$execute$0(ResourceConstrainedExecutorServiceExecutionStrategy.java:69) [otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]
15:16:05.577 INFO (ExecutionStrategy.java:44) Exception while fetching data
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Double
	at org.opentripplanner.index.IndexGraphQLSchema.lambda$new$150(IndexGraphQLSchema.java:2134) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:42) ~[otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
	at org.opentripplanner.index.ResourceConstrainedExecutorServiceExecutionStrategy.lambda$execute$0(ResourceConstrainedExecutorServiceExecutionStrategy.java:69) [otp-1.1.0-SNAPSHOT-shaded.jar:1.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_101]

**Comment by samuliheljo** [comment]
So problems:
Current master build does not work because of ResourceConstrainedExecutorServiceExecutionStrategy.countResolve() override

If I comment that out, I can get master to build. After that, UI master works with OTP master.
However, UI does not work with OTP DT-1410-node-limiting branch.

**Comment by Macroz** [comment]
Ok I think there was a mixup and the couple commits ended up in master already. 

However, the version of `graphql-java` I packaged for us was also too old. Now I have updated the republished version `execution-limits` to a later one, so if you update the dependencies and rebuild, it should work. I get the nearest tab results after using the new jars.

**Comment by samuliheljo** [comment]
Cool, seems to work now.

**Pull request merged**
