### PR TITLE
Local version of #156

### PR DESCRIPTION
**Pull request by hannesj**
Fixes correct type and adds a couple of additional fields.

### CODE REVIEW

**Comment by PasiSalenius** [comment]
Will you be deprecating serviceDay throughout the graphQL API or only here?

I don't know if switching to OTP's serviceDate will make it any easier on the Digitransit API user side... It would be nice to have a consistent API with the same property available everywhere, stoptimes etc.

**Comment by hannesj** [comment]
OTP has two different concepts. 

ServiceDay, which is the moment of midnight (approximately) and is only used in the Stoptime type. This can be used to add to the various times to get the unix timestamp for the scheduled/realtime arrival/departure times. 

ServiceDate, which is used elsewhere. and is the YYYYMMDD of the date when the service is running (liikennöintivuorokausi in Finnish).

In this case we used to have a field serviceDay, which actually took the serviceDate as an input parameter and was renamed to match the usage in other places.

**Comment by PasiSalenius** [comment]
Okay to be a bit more specific, what I need here is the value that I need to add to the arrival/departure times to get the unix timestamps. I did find a way to do this via Leg startTime, but it involves asking for a list of stoptimes and then fixing these with the correct serviceDay value. Thought that it would be nicer to get this value straight from the Leg itself, as OTP must know this value anyway.

**Comment by hannesj** [comment]
For what part do you want to know the departure times? The only types which use that is stoptime, which already has the serviceDay available.

If you want to show departure/arrival times for the intermediate stops, I added a field intermediatePlaces which can be used to fetch the intermediate stops as place type which includes departure and arrival times. Is this suitable for you to use?

**Comment by PasiSalenius** [comment]
I wanted to perform a route planning query and receive itineraries with transit legs, with the intermediate stoptimes in them. But sounds like you just solved my issue by including the intermediatePlaces field in route leg. This was a bit cumbersome to do get right before.

**Comment by hannesj** [comment]
Good.

For the second point, there is no easy answer. As the trip is just the generic trip for any date, we can't include any serviceDay by default, and you will get the scheduled arrival/departure times. Those times are just seconds from the midnight, as the trip can be repeated daily. I hope intermediatePlaces solves also your issue here. You can also query the serviceDate and use a separate trip query with the trip id and service date from the leg.

**Comment by PasiSalenius** [comment]
Yeah exactly, it will be nice to be able to use that serviceDate directly in following stoptimes queries. Thanks for fixing this!

**Pull request merged**
